export interface AppItem {
  module_id?: number;
  module_name: string;
  module_alias: string;
  module_desc: string;
  module_icon?: string;
  module_version?: string;
  module_priority: number;
  module_source: 'official' | 'third_party' | 'custom';
  module_status: 0 | 1; // 0禁用, 1启用
  module_is_core: 0 | 1; // 0否, 1是
  module_is_installed: 0 | 1; // 0否, 1是
  module_installed_at?: string;
  module_author?: string;
  module_author_email?: string;
  module_homepage?: string;
  module_keywords: string[];
  module_providers?: string[];
  module_dependencies?: string[];
}

// Mock 数据
export const mockApps: AppItem[] = [
  {
    module_id: 1,
    module_name: 'Base',
    module_alias: '基础服务',
    module_desc:
      'LaravelAPI 基础服务，提供用户认证、权限管理、日志记录等核心功能',
    module_icon: 'AppstoreOutlined',
    module_version: '1.0.0',
    module_priority: 100,
    module_source: 'official',
    module_status: 1,
    module_is_core: 1,
    module_is_installed: 1,
    module_installed_at: '2025-01-01 00:00:00',
    module_author: 'GPA Team',
    module_keywords: ['基础', '认证', '权限'],
  },
  {
    module_id: 2,
    module_name: 'Sms',
    module_alias: '短信服务',
    module_desc: '提供短信发送、验证码管理等功能，支持多种短信服务商',
    module_icon: 'MessageOutlined',
    module_version: '1.0.0',
    module_priority: 90,
    module_source: 'official',
    module_status: 1,
    module_is_core: 0,
    module_is_installed: 1,
    module_installed_at: '2025-01-01 00:00:00',
    module_author: 'GPA Team',
    module_keywords: ['短信', '验证码', '通知'],
  },
  {
    module_id: 3,
    module_name: 'Payment',
    module_alias: '支付服务',
    module_desc: '集成多种支付方式，包括支付宝、微信支付、银联等',
    module_icon: 'PayCircleOutlined',
    module_version: '1.0.0',
    module_priority: 85,
    module_source: 'third_party',
    module_status: 1,
    module_is_core: 0,
    module_is_installed: 1,
    module_author: 'Third Party',
    module_keywords: ['支付', '支付宝', '微信'],
  },
  {
    module_id: 4,
    module_name: 'Oss',
    module_alias: '对象存储',
    module_desc: '支持阿里云OSS、腾讯云COS、七牛云等对象存储服务',
    module_icon: 'CloudUploadOutlined',
    module_version: '1.0.0',
    module_priority: 80,
    module_source: 'third_party',
    module_status: 1,
    module_is_core: 0,
    module_is_installed: 1,
    module_author: 'Third Party',
    module_keywords: ['存储', 'OSS', '文件'],
  },
  {
    module_id: 5,
    module_name: 'Notification',
    module_alias: '消息通知',
    module_desc: '统一的消息通知服务，支持邮件、短信、站内信等多种通知方式',
    module_icon: 'BellOutlined',
    module_version: '1.0.0',
    module_priority: 75,
    module_source: 'official',
    module_status: 0,
    module_is_core: 0,
    module_is_installed: 1,
    module_author: 'GPA Team',
    module_keywords: ['通知', '消息', '邮件'],
  },
  {
    module_id: 6,
    module_name: 'Analytics',
    module_alias: '数据分析',
    module_desc: '提供数据统计、分析报表等功能，帮助了解业务运营情况',
    module_icon: 'LineChartOutlined',
    module_version: '1.0.0',
    module_priority: 70,
    module_source: 'third_party',
    module_status: 1,
    module_is_core: 0,
    module_is_installed: 1,
    module_author: 'Third Party',
    module_keywords: ['分析', '统计', '报表'],
  },
  {
    module_id: 7,
    module_name: 'Search',
    module_alias: '搜索服务',
    module_desc: '全文搜索服务，支持 Elasticsearch、Algolia 等搜索引擎',
    module_icon: 'SearchOutlined',
    module_version: '1.0.0',
    module_priority: 65,
    module_source: 'third_party',
    module_status: 0,
    module_is_core: 0,
    module_is_installed: 0,
    module_author: 'Third Party',
    module_keywords: ['搜索', '全文', 'ES'],
  },
  {
    module_id: 8,
    module_name: 'Cache',
    module_alias: '缓存服务',
    module_desc: '高性能缓存服务，支持 Redis、Memcached 等缓存系统',
    module_icon: 'ThunderboltOutlined',
    module_version: '1.0.0',
    module_priority: 60,
    module_source: 'official',
    module_status: 1,
    module_is_core: 0,
    module_is_installed: 1,
    module_author: 'GPA Team',
    module_keywords: ['缓存', 'Redis', '性能'],
  },
  {
    module_id: 9,
    module_name: 'Queue',
    module_alias: '队列服务',
    module_desc: '异步任务队列服务，支持 RabbitMQ、Kafka 等消息队列',
    module_icon: 'OrderedListOutlined',
    module_version: '1.0.0',
    module_priority: 55,
    module_source: 'official',
    module_status: 1,
    module_is_core: 0,
    module_is_installed: 1,
    module_author: 'GPA Team',
    module_keywords: ['队列', '异步', '任务'],
  },
  {
    module_id: 10,
    module_name: 'Log',
    module_alias: '日志服务',
    module_desc: '集中式日志管理服务，支持日志收集、查询、分析等功能',
    module_icon: 'FileTextOutlined',
    module_version: '1.0.0',
    module_priority: 50,
    module_source: 'third_party',
    module_status: 0,
    module_is_core: 0,
    module_is_installed: 0,
    module_author: 'Third Party',
    module_keywords: ['日志', '收集', '分析'],
  },
  {
    module_id: 11,
    module_name: 'Monitor',
    module_alias: '监控服务',
    module_desc: '系统监控服务，提供性能监控、告警通知等功能',
    module_icon: 'DashboardOutlined',
    module_version: '1.0.0',
    module_priority: 45,
    module_source: 'third_party',
    module_status: 1,
    module_is_core: 0,
    module_is_installed: 1,
    module_author: 'Third Party',
    module_keywords: ['监控', '性能', '告警'],
  },
  {
    module_id: 12,
    module_name: 'ApiGateway',
    module_alias: 'API网关',
    module_desc: 'API 网关服务，提供路由、限流、鉴权等功能',
    module_icon: 'ApiOutlined',
    module_version: '1.0.0',
    module_priority: 40,
    module_source: 'official',
    module_status: 0,
    module_is_core: 0,
    module_is_installed: 0,
    module_author: 'GPA Team',
    module_keywords: ['网关', 'API', '路由'],
  },
];
